/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

// define RGB
#define DRIVER_LED_TOTAL 8
#define RGB_MATRIX_LED_COUNT 8
#define RGBLED_NUM 8

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
